---
- hosts: all
  become: true
#  pre_tasks:
#  - name: Import secure vars
#    include_vars: secure_vars/{{ secure_vars_file }}
#    when: secure_vars_file is defined
  roles:
  - base
  - nginx
  - git
  - php-repo-sury
  - php-cli
  - composer
  - node
  - yarn
  post_tasks:
  - name: restart sshd
    service: name=ssh state=restarted enabled=yes
    when: sshd_status.changed
